version: '3.8'
services:
  my-app:
    image: my-app:1.0
    container_name: my-app
    ports:
      - 3000:3000
    environment:
      - DOCKER_COMPOSE=true  # Set environment variable to indicate it's running inside Docker Compose
    depends_on:
      - mongo  # Ensure mongo is started before my-app

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo

volumes:
  mongo-data:
    driver: local
